[2023-12-26T08:17:46.014+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2023-12-26T08:17:44.214501+00:00 [queued]>
[2023-12-26T08:17:46.057+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2023-12-26T08:17:44.214501+00:00 [queued]>
[2023-12-26T08:17:46.059+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-26T08:17:46.132+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): dbt_run> on 2023-12-26 08:17:44.214501+00:00
[2023-12-26T08:17:46.141+0000] {standard_task_runner.py:60} INFO - Started process 3963 to run task
[2023-12-26T08:17:46.153+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_run', 'manual__2023-12-26T08:17:44.214501+00:00', '--job-id', '5091', '--raw', '--subdir', 'DAGS_FOLDER/first_dat.py', '--cfg-path', '/tmp/tmptyn4bc7e']
[2023-12-26T08:17:46.176+0000] {standard_task_runner.py:88} INFO - Job 5091: Subtask dbt_run
[2023-12-26T08:17:46.391+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag.dbt_run manual__2023-12-26T08:17:44.214501+00:00 [running]> on host 29b3723064ac
[2023-12-26T08:17:46.778+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abrham' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T08:17:44.214501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T08:17:44.214501+00:00'
[2023-12-26T08:17:46.779+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-26T08:17:46.780+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir ../dbt_warehouse']
[2023-12-26T08:17:46.830+0000] {subprocess.py:86} INFO - Output:
[2023-12-26T08:17:46.833+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2023-12-26T08:17:46.841+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-26T08:17:46.866+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-26T08:17:46.879+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_run, execution_date=20231226T081744, start_date=20231226T081746, end_date=20231226T081746
[2023-12-26T08:17:46.951+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5091 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 3963)
[2023-12-26T08:17:46.987+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T08:17:47.125+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
